[custom]
enable_rule_generator=true

custom_proxy_group=PROXY`select`[]🇭🇰 高级`[]🇭🇰 标准`[]🇭🇰 实验`[]🇯🇵 高级`[]🇯🇵 标准`[]🇯🇵 实验`[]🇺🇸 高级`[]🇺🇸 标准`[]🇺🇸 实验`[]🇸🇬 高级`[]🇸🇬 标准`[]🇸🇬 实验`(^(?!(🇭🇰|香港)|(🇯🇵|日本)|(🇺🇸|美国)|(🇸🇬|新加坡)))
custom_proxy_group=🇭🇰 高级`url-test`((🇭🇰|香港).*高级)`http://91.108.56.190`1800,2,50
custom_proxy_group=🇭🇰 标准`url-test`((🇭🇰|香港).*标准)`http://91.108.56.190`1800,2,50
custom_proxy_group=🇭🇰 实验`url-test`((🇭🇰|香港).*实验)`http://91.108.56.190`1800,2,50
custom_proxy_group=🇯🇵 高级`url-test`((🇯🇵|日本).*高级)`http://91.108.56.190`1800,2,50
custom_proxy_group=🇯🇵 标准`url-test`((🇯🇵|日本).*标准)`http://91.108.56.190`1800,2,50
custom_proxy_group=🇯🇵 实验`url-test`((🇯🇵|日本).*实验)`http://91.108.56.190`1800,2,50
custom_proxy_group=🇺🇸 高级`url-test`((🇺🇸|美国).*高级)`http://91.108.56.190`1800,2,50
custom_proxy_group=🇺🇸 标准`url-test`((🇺🇸|美国).*标准)`http://91.108.56.190`1800,2,50
custom_proxy_group=🇺🇸 实验`url-test`((🇺🇸|美国).*实验)`http://91.108.56.190`1800,2,50
custom_proxy_group=🇸🇬 高级`url-test`((🇸🇬|新加坡).*高级)`http://91.108.56.190`1800,2,50
custom_proxy_group=🇸🇬 标准`url-test`((🇸🇬|新加坡).*标准)`http://91.108.56.190`1800,2,50
custom_proxy_group=🇸🇬 实验`url-test`((🇸🇬|新加坡).*实验)`http://91.108.56.190`1800,2,50
custom_proxy_group=AI`select`[]PROXY`[]DIRECT`[]🇭🇰 高级`[]🇭🇰 标准`[]🇭🇰 实验`[]🇯🇵 高级`[]🇯🇵 标准`[]🇯🇵 实验`[]🇺🇸 高级`[]🇺🇸 标准`[]🇺🇸 实验`[]🇸🇬 高级`[]🇸🇬 标准`[]🇸🇬 实验`(^(?!(🇭🇰|香港)|(🇯🇵|日本)|(🇺🇸|美国)|(🇸🇬|新加坡)))
custom_proxy_group=Other`select`[]DIRECT

ruleset=Other,[]FINAL

surge_rule_base=https://raw.githubusercontent.com/Bearxxuan/Sub_Ruleset/master/Surge/onlyai.conf

rename=^([^=]*)=.*$@$1
rename=\s?\\t\s?@
rename=\s?动画疯@
rename=(Netflix|nf|NF)@★
rename=\s?Hulu@
rename=\s?HBO@
rename=\s?CN2-GIA@
rename=\s?TVB@
rename=\s?CN2-GI@
rename=\s?HiNet@
rename=Equinix\s?HK2\s?@
rename=\s?[0-9]{0,6}Mbps@
rename=\s?[0-9]{0,2}Gbps@
rename=\s?\[?\s?[0-9]{0,2}倍\]?@
rename=CNIX\s?-\s?@
rename=云\s?-\s?@
rename=Новосиби́рская\s?о́бласть\s?Советский\s?район\s?Ростелеком\s?@
rename=전라북도\s?전주시\s?@
rename=まつやまし\s?auひかり\s?ホーム1ギガ\s?@
rename=ソフトバンク\s?@
rename=オプテージ\s?@
rename=油尖旺御金·国峯\s?@
rename=Hinet固接\s?@
rename=Fortaleza\s?Brasil\s?Telecom\s?@
rename=布宜诺斯艾利斯\s?@
rename=Equinix-TY8\s?@
rename=无法翻墙\s?@
rename=ぜんにっぽんくうゆ\s?-\s?@
rename=爱奇艺/QQ音乐/网易云VIP/腾讯视频@
rename=中国-日本\s?多协议标签交换虚拟专用网@中日 虚拟
rename=ASYNCHRONOUS\sTRANSFERMODE\s永久虚通路连接@
rename=香港元朗\s?電訊盈科@香港元朗
rename=中港专线\s?IPLC@中港 IPLC
rename=中国-(.*?\s)@$1


;rename=!!GROUPID=3!!.*@Unblock

exclude_remarks=(如遇收费|无试用节点|官网|剩余流量|过期|遇收费|用户群|邀请|倒卖)
